### ISSUE TITLE
BR: Shadow clipping at menu top

### ISSUE THREAD

**Issue by churnish** [aaaaalexis/obsidian-baseline#126]
Minor visual bug:

<img src="https://github.com/user-attachments/assets/9e6ecbf5-f44b-4960-b4c6-bbc8880614f0" height="400">

<details><summary>Debug info</summary>
<p>

```
SYSTEM INFO:
	Obsidian version: v1.10.2
	Installer version: v1.9.14
	Operating system: Darwin Kernel Version 25.0.0: Wed Sep 17 21:41:26 PDT 2025; root:xnu-12377.1.9~141/RELEASE_ARM64_T6041 25.0.0
	Login status: logged in
	Language: en
	Catalyst license: supporter
	Insider build toggle: on
	Live preview: on
	Base theme: adapt to system
	Community theme: Baseline v1.5.5
	Snippets enabled: 75
	Restricted mode: off
	Plugins installed: 69
	Plugins enabled: 54
		1: Templater v2.16.2
		2: Style Settings v1.0.9
		3: Hider v1.5.1
		4: Pane Relief v0.5.9
		5: Collapsible Code Blocks v1.0.5
		6: Hotkeys for Bookmarks v1.1.1
		7: Quick Switcher++ v5.3.1
		8: Quiet Outline v0.4.3
		9: Lazy Plugin Loader v1.0.21
		10: Collapse Backlinks v1.0.0
		11: Reveal Active File Button v2.0.3
		12: Advanced URI v1.46.0
		13: Excalidraw v2.16.1
		14: Feed Bases v0.1.0
		15: Tab Switcher v1.4.0
		16: Advanced Canvas v5.6.2
		17: Better Word Count v0.10.1
		18: Commander v0.5.4
		19: Datacore v0.1.28
		20: Emoji Autocomplete v1.4.1
		21: Folder notes v1.8.17
		22: Hover Editor v0.11.26
		23: Image Captions v1.1.6
		24: Linter v1.30.0
		25: List Callouts v1.2.9
		26: Multi Properties v1.2.2
		27: Outliner v4.9.0
		28: Pretty Properties v1.8.9
		29: Query Control v0.7.13
		30: Shrink pinned tabs v1.0.7
		31: Sidebar Resizer v1.0.11
		32: Slash Commander v0.3.8
		33: Tabs v1.1.8
		34: Tasks v7.22.0
		35: Vertical Tabs v0.16.5
		36: Virtual Content v1.0.24
		37: Frontmatter Markdown Links v2.6.17
		38: Media Slider v1.3.4
		39: Sidebar Highlights v1.31.0
		40: Create Note in Folder v1.12.4
		41: Notebook Navigator v1.7.3
		42: Block Link Plus v1.7.6
		43: Carry-Forward v1.4.5
		44: Checklist Reset v1.3.1
		45: Group Snippets v1.10.3
		46: Image Toolkit v1.4.3
		47: Quick Tagger v2.2.3
		48: Smart Random Note v0.2.1
		49: BRAT v1.3.0
		50: Tag Wrangler v0.6.4
		51: Text Format v3.1.0
		52: Text Transporter v1.0.12
		53: Trash Explorer v1.2.3
		54: Zoom v1.1.2

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

```

</p>
</details> 

<details><summary>Style Settings</summary>
<p>

```
{
  "baseline-style@@color-scheme-dark": "default-dark",
  "baseline-style@@density-modifier": 0.75,
  "baseline-style@@radius-modifier": 1,
  "baseline-style@@layout-style": "layout-cupertino",
  "baseline-style@@input-style": "input-cupertino",
  "baseline-style@@status-bar-style": "status-bar-baseline",
  "baseline-style@@mobile-style": "mobile-immersive",
  "baseline-style@@anim-speed-modifier": 1,
  "baseline-style@@tabs-style": "tabs-floating",
  "baseline-style@@labeled-tabs": "labeled-tabs-off",
  "baseline-style@@stacked-nav-off": true,
  "baseline-style@@compact-actions-off": true,
  "baseline-style@@file-header-visibility": "view-header-title-always",
  "baseline-style@@file-header-justify": "center",
  "baseline-style@@nav-item-active-style": "nav-item-subtle",
  "baseline-style@@colorful-folders": "colorful-folders-off",
  "baseline-style@@bold-folders": true,
  "baseline-style@@nav-indentation-guide-width": "1px",
  "baseline-style@@nav-indentation-guide-color": "rgba(var(--mono-rgb-100), 0.12)",
  "baseline-style@@focus-view": "focus-view-off",
  "baseline-style@@active-line-style": "active-line-block",
  "baseline-style@@active-line-color": "active-line-color-default",
  "baseline-style@@indentation-guide-width": "1px",
  "baseline-style@@indentation-guide-color": "rgba(var(--mono-rgb-100), 0.12)",
  "baseline-style@@metadata-style": "metadata-default",
  "baseline-style@@metadata-link-nowrap": true,
  "baseline-style@@metadata-label-width-modifier": 1,
  "baseline-style@@readable-spacing": true,
  "baseline-style@@readable-spacing-modifier": 1,
  "baseline-style@@colorful-headings": "colorful-headings-off",
  "baseline-style@@h1-font": "Inter",
  "baseline-style@@h1-variant": "normal",
  "baseline-style@@h1-style": "normal",
  "baseline-style@@h1-transform": "normal",
  "baseline-style@@h2-font": "Inter",
  "baseline-style@@h3-font": "Inter",
  "baseline-style@@h4-font": "Inter",
  "baseline-style@@h5-font": "Inter",
  "baseline-style@@h6-font": "Inter",
  "baseline-style@@bases-toolbar-label-display": "none",
  "baseline-style@@bases-table-header-icon-display": "flex",
  "baseline-style@@bases-table-align-items": "start",
  "baseline-style@@blockquote-style": "blockquote-baseline",
  "baseline-style@@blockquote-font-style": "normal",
  "baseline-style@@callouts-style": "callouts-default",
  "baseline-style@@code-line-numbers": true,
  "baseline-style@@embed-style": "embed-block",
  "baseline-style@@embed-border-thickness": 2,
  "baseline-style@@link-decoration": "underline",
  "baseline-style@@link-external-decoration": "underline",
  "baseline-style@@img-grid": true,
  "baseline-style@@media-muted": 0.7,
  "baseline-style@@full-width-media-off": true,
  "baseline-style@@zoom-off": true,
  "baseline-style@@pdf-muted": 0.7,
  "baseline-style@@pdf-invert-dark": true,
  "baseline-style@@table-tabular": true,
  "baseline-style@@table-numbers": true,
  "baseline-style@@table-text-align-header": "start",
  "baseline-style@@table-text-align-body": "start",
  "baseline-style@@row-hover": true,
  "baseline-style@@tag-radius": "8px",
  "baseline-style@@checkbox-radius": "4px"
}
``` 

</p>
</details>

**Comment by churnish** [comment]
Noticed this issue on desktop as well:

<img width="335" height="233" alt="Image" src="https://github.com/user-attachments/assets/068007b7-3c1e-4816-b3ae-9827427a233b" />

<details><summary>Debug info</summary>
<p>

```
SYSTEM INFO:
	Obsidian version: v1.10.2
	Installer version: v1.9.14
	Operating system: Darwin Kernel Version 25.0.0: Wed Sep 17 21:41:26 PDT 2025; root:xnu-12377.1.9~141/RELEASE_ARM64_T6041 25.0.0
	Login status: logged in
	Language: en
	Catalyst license: supporter
	Insider build toggle: on
	Live preview: on
	Base theme: adapt to system
	Community theme: Baseline v1.5.5
	Snippets enabled: 75
	Restricted mode: off
	Plugins installed: 69
	Plugins enabled: 55
		1: Templater v2.16.2
		2: Style Settings v1.0.9
		3: Hider v1.5.1
		4: Pane Relief v0.5.9
		5: Collapsible Code Blocks v1.0.5
		6: Hotkeys for Bookmarks v1.1.1
		7: Quick Switcher++ v5.3.1
		8: Quiet Outline v0.4.3
		9: Lazy Plugin Loader v1.0.21
		10: Collapse Backlinks v1.0.0
		11: Reveal Active File Button v2.0.3
		12: Advanced URI v1.46.0
		13: Excalidraw v2.16.1
		14: Feed Bases v0.1.0
		15: Tab Switcher v1.4.0
		16: Advanced Canvas v5.6.2
		17: Better Word Count v0.10.1
		18: Commander v0.5.4
		19: Datacore v0.1.28
		20: Emoji Autocomplete v1.4.1
		21: Folder notes v1.8.17
		22: Hover Editor v0.11.26
		23: Image Captions v1.1.6
		24: Linter v1.30.0
		25: List Callouts v1.2.9
		26: Multi Properties v1.2.2
		27: Outliner v4.9.0
		28: Pretty Properties v1.8.9
		29: Query Control v0.7.13
		30: Shrink pinned tabs v1.0.7
		31: Sidebar Resizer v1.0.11
		32: Slash Commander v0.3.8
		33: Tabs v1.1.8
		34: Tasks v7.22.0
		35: Vertical Tabs v0.16.5
		36: Virtual Content v1.0.24
		37: Frontmatter Markdown Links v2.6.17
		38: Media Slider v1.3.4
		39: Sidebar Highlights v1.31.0
		40: Create Note in Folder v1.12.4
		41: Notebook Navigator v1.7.3
		42: Block Link Plus v1.7.6
		43: Carry-Forward v1.4.5
		44: Checklist Reset v1.3.1
		45: Group Snippets v1.10.3
		46: Image Toolkit v1.4.3
		47: Quick Tagger v2.2.3
		48: Smart Random Note v0.2.1
		49: BRAT v1.3.0
		50: Tag Wrangler v0.6.4
		51: Text Format v3.1.0
		52: Text Transporter v1.0.12
		53: Trash Explorer v1.2.3
		54: Zoom v1.1.2
		55: First Line is Title v3.8.0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

</p>
</details> 

Same style settings.

**Comment by svnaxis** [comment]
Fixed on 3.0.0

**Comment by churnish** [comment]
Issue persists on desktop on my end. Ver. 3.0.1.

<img width="315" height="246" alt="Image" src="https://github.com/user-attachments/assets/ccc21459-eed9-4143-8cd9-0e829a7aeba0" />

**Comment by svnaxis** [comment]
<img width="230" height="168" alt="Image" src="https://github.com/user-attachments/assets/13fa933a-3187-4f9f-87c8-3e062c236493" />

Seems to be fine on my end, share Style Settings?

**Comment by churnish** [comment]
Can repro with the style settings I shared above, and with both sidebars collapsed.

**Comment by svnaxis** [comment]
Oh okay I thought it's just in macOS layout. Fixed for next update
