### ISSUE TITLE
Colorful Frame makes left sidebar toggle invisible when sidebar is open

### ISSUE THREAD

**Issue by paddymcd90** [aaaaalexis/obsidian-baseline#156]
**Environment:**
- Obsidian: v1.10.6
- Baseline theme: 3.0.6
- OS: macOS 26.1

**Issue:**
When Colorful Frame is enabled in Style Settings, the left sidebar toggle icon becomes invisible when the sidebar is open. The icon remains clickable but is not visible.

**Steps to reproduce:**
1. Enable Colorful Frame (Style Settings > Baseline Theme > Colors and Frames > Colorful Frame)
2. Open left sidebar
3. Observe: Left sidebar toggle icon is invisible
4. Close sidebar - icon becomes visible
5. Reopen sidebar - icon becomes invisible again

**Root cause:**
The Colorful Frame CSS rule sets `--icon-color: var(--colorful-frame-content-color)` on the sidebar toggle button, which causes the icon color to match the frame background color when the sidebar is open.

The problematic rule appears to be in the massive selector starting with:
`body.colorful-frame.is-hidden-frameless:not(.is-mobile)...` 
targeting `.sidebar-toggle-button`

**Expected behavior:**
Sidebar toggle icon should remain visible in all states when Colorful Frame is enabled.

**Screenshots:**

<img width="1743" height="1690" alt="Image" src="https://github.com/user-attachments/assets/f282017c-18e9-4389-9c82-08f4af67d732" />

<img width="1743" height="1690" alt="Image" src="https://github.com/user-attachments/assets/ba5473ec-b5dd-4650-b3d7-9819d933c41e" />

**Comment by svnaxis** [comment]
Fixed on 3.1.0. There are still some issues with Cupertino styles and colorful frame but I haven;t got around to solve them yet.

**Comment by paddymcd90** [comment]
Thanbk you, but the problem was not fixed on my machine after updating to 3.1.0.1.

**Comment by svnaxis** [comment]
I'll make some changes next update

**Comment by svnaxis** [comment]
Can you check again with 3.1.1?

**Comment by paddymcd90** [comment]
Sorry, no visible change after updating and restarting.

**Comment by svnaxis** [comment]
Seems to work normally for me in 3.1.1.0, do you mind share a screen recording showcasing the issue?

**Comment by paddymcd90** [comment]
https://github.com/user-attachments/assets/410947bf-fd8c-4f41-88d4-98622aa89976

Sure, here you go!

**Comment by svnaxis** [comment]
I've made some changes on 3.1.2, if it still happens you might want to wait for Obsidian update, the issue doesn't seem to happen on Obsidian 1.11+

**Comment by paddymcd90** [comment]
Thanks, it’s still not working but I’m absolutely fine waiting for 1.11.  Thanks for all of your work on this!

**Comment by svnaxis** [comment]
Follow up on this: Colorful frame is removed on 3.2.0 and likely won't be added back in future updates

**Comment by svnaxis** [comment]
Another update: Colorful frame is add back on 3.2.1 as "Tinted frame"
